### ISSUE TITLE
Are we not updating / maintaining this anymore?

### ISSUE THREAD

**Issue by shobhitchittora** [ReactBangalore/MeetupsData#1]
😄

**Comment by akiran** [comment]
We are planning on launching a website in August with all details about past and future meetup events.

**Comment by shobhitchittora** [comment]
@akiran That's great. Need any help building that ?

**Comment by akiran** [comment]
@shobhitchittora Its already built. We deploy soon and announce on Aug 11th

**Comment by shobhitchittora** [comment]
@akiran Thanks for letting me know. Kudos! 🎉
